name: Rentz Pages CI

on:
  pull_request:
    branches: [ dev ]

jobs:
  composer-npm-migrations:

    runs-on: ubuntu-latest

    services:
        mysql:
            image: mysql:8
            env:
                MYSQL_ALLOW_EMPTY_PASSWORD: yes
                MYSQL_DATABASE: rentz
            ports:
                - 3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Change PHP to 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, bcmath
    - name: Downgrade Composer
      run: sudo composer self-update --2
    - name: Install Composer Dependencies
      env:
        COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Run PHPStan(Static Analysis)
      run: php -d memory_limit=-1 ./vendor/bin/phpstan analyse
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run Migrations
      run: php artisan migrate --force
      env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
    - name: Specify Node Version
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install NPM Dependencies
      run: npm install
    - name: Build Frontend Assets
      run: npm run prod
